# Zero to Hero in Neovim

{{< qrcode https://github.com/jmbuhr/nvim-zero-to-hero >}}

## Structure

- first: general tips and tricks you can use in any vim
- second: configuring neovim and learning lua
- third: write a small "plugin" in lua to play a sound

## Installation

<https://github.com/neovim/neovim>

- Go to: <https://github.com/neovim/neovim/releases/tag/stable>
- download latest release for your system
  - On windows, I recommend WSL2 and then continue like on linux, then you have a nice terminal as well (otherwise its also fine to use the msi)
  - for linux, I recommend the appimage nvim.appimage
  - download it to somewhere on your path and make it executable, e.g.

```bash
sudo wget https://github.com/neovim/neovim/releases/download/stable/nvim.appimage -O /usr/bin/nvim && sudo chmod +x /usr/bin/nvim
```

- execute with nvim
- if you are on ubuntu and the appimage doesn't start, run `sudo apt install libfuse2`

## Setup, Configuration

<https://github.com/jmbuhr/quarto-nvim-kickstarter>

Download the [kickstarter configuration](https://github.com/jmbuhr/quarto-nvim-kickstarter)!

```bash
git clone https://github.com/jmbuhr/quarto-nvim-kickstarter.git ~/.config/nvim
```

open Neovim with `nvim` and let it automatically install plugins.

## Example Files

```bash
git clone https://github.com/jmbuhr/nvim-zero-to-hero.git
```

In `files/`

- `example.mdp`
- `template.mdp`

## Tip

remap capslock to escape!

## Modes

- `<esc>`
- `i`
- `v`
- `<c-v>`

## Movement and Operators

Vim is a language

- `:`

- `jk`
- `hl`
- `wW` and `bB`
- `ft` and `FT` and `;`
- `/?` and `nN`
- `0$`

- `aA`
- `iI`
- `oO`
- `y`
- `d`
- `x`
- `p`
- `c`

- `v`
- `vi` (`ip`, `is`)
- `va` 

- `u`

- `.`
- `m`


## Our own Lua Neovim Plugin Example

<https://en.wikipedia.org/wiki/Kookaburra>


# Further reading (or viewing)

- [on the official quarto site](https://quarto.org/docs/get-started/hello/neovim.html)
- [behind the scenes 🦦](https://github.com/jmbuhr/otter.nvim)
- [further customization](https://github.com/jmbuhr/.dotfiles/tree/main/nvim/.config) e.g. for gromacs filetypes and the marksman language server
- [fonts with icons for your terminal](https://www.nerdfonts.com/)
- [vim keybindings in your browser](https://github.com/philc/vimium)


<iframe width="560" height="315" src="https://www.youtube.com/embed/videoseries?list=PLabWm-zCaD1axcMGvf7wFxJz8FZmyHSJ7" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

And optionally also for [tmux](https://github.com/jmbuhr/tmux-kickstarter)

```bash
cd ~
wget https://raw.githubusercontent.com/jmbuhr/tmux-kickstarter/main/.tmux.conf
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
```

followed by `tmux` and `ctrl + space` followed by `I`.




